[build-system]
# requires = [
#     "scikit-build-core",
#     "pybind11",
# ]
# build-backend = "scikit_build_core.build"
requires = ["setuptools", "cffi"]
build-backend = "setuptools.build_meta"

[project]
name = "lattice-symmetries"
version = "3.0.0"
authors = [{ name = "Tom Westerhout", email = "14264576+twesterhout@users.noreply.github.com" }]
description = "A package to simplify working with symmetry-adapted quantum many-body bases."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "cffi",
    "loguru",
    "more-itertools",
    "numpy",
    "scipy",
    "sympy"
    # NOTE: Adding Halide here generates a bunch of problems which I don't know how
    # to solve at the moment, so for now one has to do a separate pip install
    # of Halide
]

[project.urls]
Homepage = "https://github.com/twesterhout/lattice-symmetries"
Issues = "https://github.com/twesterhout/lattice-symmetries/issues"
Documentation = "https://github.com/twesterhout/lattice-symmetries/README.md"
Repository = "https://github.com/twesterhout/lattice-symmetries.git"

[tool.setuptools.package-data]
lattice_symmetries = ["liblattice_symmetries_chapel.*"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
