name: Testing
on:
  pull_request:
  push:
    branches: [concise, master]
jobs:
  tests:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest # x64
          - os: ubuntu-24.04-arm # arm64
          - os: macos-latest # arm64
          - os: macos-13 # x64 
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: twesterhout
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build lattice-symmetries (Python 3.12)
        run: |
          nix build --option max-jobs 1 --option cores 2 --accept-flake-config -L .#python312Packages.lattice-symmetries
      - name: Build lattice-symmetries (Python 3.11)
        run: |
          nix build --option max-jobs 1 --option cores 2 --accept-flake-config -L .#python311Packages.lattice-symmetries
  containers:
    needs: tests
    name: Build Apptainer and Docker containers on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest # x64
          - os: ubuntu-24.04-arm # arm64
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build Docker container
        run: |
          nix build --option max-jobs 1 --option cores 2 --accept-flake-config -L .#docker
